function ddpcom = ddpcom(params,x,z)
global flags

g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;

if flags.optimize_mw
  mw = x.mw;
else
  mw = params.mw;
end

I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

d2q1 = z.ddxb;
d2q2 = z.ddyb;
d2q3 = z.ddthb;
d2q4 = z.ddlw;
d2q5 = z.ddth1;
d2q6 = z.ddth2;
d2q7 = z.ddth3;
d2q8 = z.ddth4;
d2q9 = z.ddth5;
d2q10 = z.ddth6;

%DDPCOM
%    DDPCOM = DDPCOM(A1,A2,A3,A4,A5,A6,A7,C1,C2,D2Q1,D2Q2,D2Q3,D2Q4,D2Q5,D2Q6,D2Q7,D2Q8,D2Q9,D2Q10,DQ3,DQ4,DQ5,DQ6,DQ7,DQ8,DQ9,DQ10,L1,L2,L4,L5,L7,M1,M2,M3,M4,M5,M6,M7,MW,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/15 19:53:45

t2 = cos(q3);
t3 = sin(q3);
t4 = d2q3+d2q5;
t5 = d2q3+d2q8;
t6 = dq3+dq5;
t7 = dq3+dq8;
t8 = q3+q5;
t9 = q3+q8;
t10 = dq3.^2;
t21 = -c1;
t22 = -c2;
t23 = -d2q1;
t24 = -q4;
t48 = m1+m2+m3+m4+m5+m6+m7;
t11 = d2q6+t4;
t12 = d2q9+t5;
t13 = dq6+t6;
t14 = dq9+t7;
t15 = cos(t8);
t16 = cos(t9);
t17 = q6+t8;
t18 = q9+t9;
t19 = sin(t8);
t20 = sin(t9);
t31 = t6.^2;
t32 = t7.^2;
t37 = a3+t21;
t38 = a6+t22;
t43 = l7+t24;
t55 = 1.0./t48;
t25 = cos(t17);
t26 = cos(t18);
t27 = q7+t17;
t28 = q10+t18;
t29 = sin(t17);
t30 = sin(t18);
t33 = d2q7+t11;
t34 = d2q10+t12;
t35 = dq7+t13;
t36 = dq10+t14;
t44 = t13.^2;
t45 = t14.^2;
t49 = l1.*t4.*t15;
t50 = l4.*t5.*t16;
t51 = l1.*t4.*t19;
t52 = l4.*t5.*t20;
t53 = l1.*t19.*t31;
t54 = l4.*t20.*t32;
t56 = l1.*t15.*t31;
t57 = l4.*t16.*t32;
t39 = cos(t27);
t40 = cos(t28);
t41 = sin(t27);
t42 = sin(t28);
t46 = t35.^2;
t47 = t36.^2;
t58 = -t53;
t59 = -t54;
mt1 = [-t55.*(m3.*(t23+t51+t56+l2.*t11.*t29+l2.*t25.*t44+t33.*t37.*t41+t37.*t39.*t46)+m6.*(t23+t52+t57+l5.*t12.*t30+l5.*t26.*t45+t34.*t38.*t42+t38.*t40.*t47)+m2.*(t23+t51+t56+a2.*t11.*t29+a2.*t25.*t44)+m5.*(t23+t52+t57+a5.*t12.*t30+a5.*t26.*t45)+mw.*(t23+d2q4.*t2-dq3.*dq4.*t3.*2.0+d2q3.*t3.*t43+t2.*t10.*t43)+m7.*(t23+a7.*d2q3.*t3+a7.*t2.*t10)+m1.*(t23+a1.*t4.*t19+a1.*t15.*t31)+m4.*(t23+a4.*t5.*t20+a4.*t16.*t32))];
mt2 = [t55.*(-mw.*(-d2q2+d2q4.*t3+dq3.*dq4.*t2.*2.0-d2q3.*t2.*t43+t3.*t10.*t43)+m3.*(d2q2+t49+t58+l2.*t11.*t25-l2.*t29.*t44+t33.*t37.*t39-t37.*t41.*t46)+m6.*(d2q2+t50+t59+l5.*t12.*t26-l5.*t30.*t45+t34.*t38.*t40-t38.*t42.*t47)+m2.*(d2q2+t49+t58+a2.*t11.*t25-a2.*t29.*t44)+m5.*(d2q2+t50+t59+a5.*t12.*t26-a5.*t30.*t45)+m7.*(d2q2+a7.*d2q3.*t2-a7.*t3.*t10)+m1.*(d2q2+a1.*t4.*t15-a1.*t19.*t31)+m4.*(d2q2+a4.*t5.*t16-a4.*t20.*t32))];
ddpcom = [mt1,mt2];
end
