function dJc1 = dJc1(params,x)
global flags
g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;

if flags.optimize_mw
  mw = x.mw;
else
  mw = params.mw;
end

I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

%dJc1
%    dJc1 = dJc1(DQ3,DQ5,DQ6,L1,L2,Q3,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/13 21:53:45

t2 = dq3+dq5;
t3 = q3+q5;
t4 = dq6+t2;
t5 = cos(t3);
t6 = q6+t3;
t7 = sin(t3);
t8 = cos(t6);
t9 = sin(t6);
t10 = l1.*t2.*t5;
t11 = l1.*t2.*t7;
t12 = l2.*t4.*t8;
t13 = l2.*t4.*t9;
t14 = -t10;
t15 = -t11;
t16 = -t12;
t17 = -t13;
t18 = t14+t16;
t19 = t15+t17;
dJc1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t18,t19,0.0,0.0,0.0,0.0,t18,t19,0.0,t16,t17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,10]);
end
