function dJc2 = dJc2(params,x)
global flags
g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;

if flags.optimize_mw
  mw = x.mw;
else
  mw = params.mw;
end

I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

%dJc2
%    dJc2 = dJc2(DQ3,DQ8,DQ9,L4,L5,Q3,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/07/15 19:53:48

t2 = dq3+dq8;
t3 = q3+q8;
t4 = dq9+t2;
t5 = cos(t3);
t6 = q9+t3;
t7 = sin(t3);
t8 = cos(t6);
t9 = sin(t6);
t10 = l4.*t2.*t5;
t11 = l4.*t2.*t7;
t12 = l5.*t4.*t8;
t13 = l5.*t4.*t9;
t14 = -t10;
t15 = -t11;
t16 = -t12;
t17 = -t13;
t18 = t14+t16;
t19 = t15+t17;
dJc2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t18,t19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t18,t19,0.0,t16,t17,0.0,0.0,0.0,0.0],[3,10]);
end
