function dJtoe = dJtoe(params,x,z)
global flags

g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;

if flags.optimize_mw
  mw = x.mw;
else
  mw = params.mw;
end

I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

d2q1 = z.ddxb;
d2q2 = z.ddyb;
d2q3 = z.ddthb;
d2q4 = z.ddlw;
d2q5 = z.ddth1;
d2q6 = z.ddth2;
d2q7 = z.ddth3;
d2q8 = z.ddth4;
d2q9 = z.ddth5;
d2q10 = z.ddth6;

%DJTOE
%    DJTOE = DJTOE(C1,DQ3,DQ5,DQ6,DQ7,L1,L2,L3,Q3,Q5,Q6,Q7)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Sep-2023 03:49:48

t2 = dq3+dq5;
t3 = q3+q5;
t8 = -l3;
t4 = dq6+t2;
t5 = cos(t3);
t6 = q6+t3;
t7 = sin(t3);
t14 = c1+t8;
t9 = cos(t6);
t10 = q7+t6;
t11 = sin(t6);
t12 = dq7+t4;
t16 = l1.*t2.*t5;
t17 = l1.*t2.*t7;
t13 = cos(t10);
t15 = sin(t10);
t18 = l2.*t4.*t9;
t19 = l2.*t4.*t11;
t20 = -t16;
t21 = -t17;
t22 = -t18;
t23 = -t19;
t24 = t12.*t13.*t14;
t25 = t12.*t14.*t15;
t26 = t20+t22+t24;
t27 = t21+t23+t25;
dJtoe = reshape([0.0,0.0,0.0,0.0,t26,t27,0.0,0.0,t26,t27,t22+t24,t23+t25,t24,t25,0.0,0.0,0.0,0.0,0.0,0.0],[2,10]);
