function dpj = dpj(params,x)
global flags
g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;



I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

%DPJ
%    DPJ = DPJ(C1,C2,DQ1,DQ2,DQ3,DQ5,DQ6,DQ7,DQ8,DQ9,DQ10,L1,L2,L3,L4,L5,L6,L7,Q3,Q5,Q6,Q7,Q8,Q9,Q10)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Nov-2023 16:39:03

t2 = dq3+dq5;
t3 = dq3+dq8;
t4 = q3+q5;
t5 = q3+q8;
t14 = -l3;
t15 = -l6;
t6 = dq6+t2;
t7 = dq9+t3;
t8 = cos(t4);
t9 = cos(t5);
t10 = q6+t4;
t11 = q9+t5;
t12 = sin(t4);
t13 = sin(t5);
t26 = c1+t14;
t27 = c2+t15;
t16 = cos(t10);
t17 = cos(t11);
t18 = q7+t10;
t19 = q10+t11;
t20 = sin(t10);
t21 = sin(t11);
t22 = dq7+t6;
t23 = dq10+t7;
t30 = l1.*t2.*t8;
t31 = l4.*t3.*t9;
t32 = l1.*t2.*t12;
t33 = l4.*t3.*t13;
t24 = cos(t18);
t25 = cos(t19);
t28 = sin(t18);
t29 = sin(t19);
t34 = l2.*t6.*t16;
t35 = l5.*t7.*t17;
t36 = l2.*t6.*t20;
t37 = l5.*t7.*t21;
t38 = -t32;
t39 = -t33;
t40 = -t36;
t41 = -t37;
dpj = reshape([dq1+t38,dq1+t38+t40,dq1+t38+t40+t22.*t26.*t28,dq1+t38+t40+c1.*t22.*t28,dq1+t39,dq1+t39+t41,dq1+t39+t41+t23.*t27.*t29,dq1+t39+t41+c2.*t23.*t29,dq1-dq3.*l7.*sin(q3),dq2+t30,dq2+t30+t34,dq2+t30+t34-t22.*t24.*t26,dq2+t30+t34-c1.*t22.*t24,dq2+t31,dq2+t31+t35,dq2+t31+t35-t23.*t25.*t27,dq2+t31+t35-c2.*t23.*t25,dq2+dq3.*l7.*cos(q3)],[9,2]);
