function pc = pc(params,x,z)
global flags

g = params.g;

m1 = params.m1;
m2 = params.m2;
m3 = params.m3;
m4 = params.m4;
m5 = params.m5;
m6 = params.m6;
m7 = params.m7;

I1 = params.i1;
I2 = params.i2;
I3 = params.i3;
I4 = params.i4;
I5 = params.i5;
I6 = params.i6;
I7 = params.i7;

l1 = params.l1;
l2 = params.l2;
l3 = params.l3;
l4 = params.l4;
l5 = params.l5;
l6 = params.l6;
l7 = params.l7;

a1 = params.a1;
a2 = params.a2;
a3 = params.a3;
a4 = params.a4;
a5 = params.a5;
a6 = params.a6;
a7 = params.a7;

c1 = params.c1;
c2 = params.c2;

q1 = x.xb;
q2 = x.yb;
q3 = x.thb;
q4 = x.lw;
q5 = x.th1;
q6 = x.th2;
q7 = x.th3;
q8 = x.th4;
q9 = x.th5;
q10 = x.th6;

dq1 = x.dxb;
dq2 = x.dyb;
dq3 = x.dthb;
dq4 = x.dlw;
dq5 = x.dth1;
dq6 = x.dth2;
dq7 = x.dth3;
dq8 = x.dth4;
dq9 = x.dth5;
dq10 = x.dth6;

d2q1 = z.ddxb;
d2q2 = z.ddyb;
d2q3 = z.ddthb;
d2q4 = z.ddlw;
d2q5 = z.ddth1;
d2q6 = z.ddth2;
d2q7 = z.ddth3;
d2q8 = z.ddth4;
d2q9 = z.ddth5;
d2q10 = z.ddth6;

%PC
%    PC = PC(A1,A2,A3,A4,A5,A6,A7,C1,C2,L1,L2,L4,L5,Q1,Q2,Q3,Q5,Q6,Q7,Q8,Q9,Q10)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Nov-2023 16:39:03

t2 = q3+q5;
t3 = q3+q8;
t10 = -c1;
t11 = -c2;
t4 = cos(t2);
t5 = cos(t3);
t6 = q6+t2;
t7 = q9+t3;
t8 = sin(t2);
t9 = sin(t3);
t22 = a3+t10;
t23 = a6+t11;
t12 = cos(t6);
t13 = cos(t7);
t14 = q7+t6;
t15 = q10+t7;
t16 = sin(t6);
t17 = sin(t7);
t18 = l1.*t4;
t19 = l4.*t5;
t20 = l1.*t8;
t21 = l4.*t9;
pc = reshape([q1+a1.*t4,q1+t18+a2.*t12,q1+t18+l2.*t12+t22.*cos(t14),q1+a4.*t5,q1+t19+a5.*t13,q1+t19+l5.*t13+t23.*cos(t15),q1+a7.*cos(q3),q2+a1.*t8,q2+t20+a2.*t16,q2+t20+l2.*t16+t22.*sin(t14),q2+a4.*t9,q2+t21+a5.*t17,q2+t21+l5.*t17+t23.*sin(t15),q2+a7.*sin(q3)],[7,2]);
